HEADERS += \
           $$PWD/core/base_request.h \
           $$PWD/core/base_response.h \
           $$PWD/core/gun/cms/gun_base_model.h \
           $$PWD/core/gun/cms/gun_cms.h \
           $$PWD/core/gun/cms/barrel/gun_cms_command_barrel.h \
           $$PWD/core/gun/cms/barrel/gun_command_barrel_request.h \
           $$PWD/core/gun/cms/barrel/gun_command_barrel_response.h \
           $$PWD/core/gun/cms/mode/gun_cms_command_barrel_mode.h \
           $$PWD/core/gun/cms/mode/gun_mode_barrel_request.h \
           $$PWD/core/gun/cms/mode/gun_mode_barrel_response.h \
           $$PWD/core/gun/cms/status/gun_cms_command_status.h \
           $$PWD/core/gun/cms/status/gun_command_status_request.h \
           $$PWD/core/gun/cms/status/gun_command_status_response.h \
           $$PWD/core/gun/stream/gun_stream.h \
           $$PWD/core/gun/stream/gun_stream_base.h \
           $$PWD/core/gun/stream/gun_barrel/gun_feedback_barrel_model.h \
           $$PWD/core/gun/stream/gun_barrel/gun_feedback_barrel_stream.h \
           $$PWD/core/gun/stream/gun_coverage/gun_coverage_model.h \
           $$PWD/core/gun/stream/gun_coverage/gun_coverage_stream.h \
           $$PWD/core/gun/stream/gun_status/gun_feedback_status_model.h \
           $$PWD/core/gun/stream/gun_status/gun_feedback_status_stream.h \
           $$PWD/core/osd/cms/osd_cms.h \
           $$PWD/core/osd/cms/inertia/gyro_model.h \
           $$PWD/core/osd/cms/inertia/osd_cms_gyro_data.h \
           $$PWD/core/osd/cms/inertia/osd_set_gyro_request.h \
           $$PWD/core/osd/cms/input_mode/input_mode_model.h \
           $$PWD/core/osd/cms/input_mode/osd_cms_input_mode.h \
           $$PWD/core/osd/cms/input_mode/osd_input_mode_request.h \
           $$PWD/core/osd/cms/position/osd_cms_position_data.h \
           $$PWD/core/osd/cms/position/osd_set_position_request.h \
           $$PWD/core/osd/cms/position/position_model.h \
           $$PWD/core/osd/cms/speed/osd_cms_speed_data.h \
           $$PWD/core/osd/cms/speed/osd_set_speed_request.h \
           $$PWD/core/osd/cms/speed/speed_model.h \
           $$PWD/core/osd/cms/water_speed/osd_cms_waterspeed_data.h \
           $$PWD/core/osd/cms/water_speed/osd_set_waterspeed_request.h \
           $$PWD/core/osd/cms/water_speed/waterspeed_model.h \
           $$PWD/core/osd/cms/weather/osd_cms_weather_data.h \
           $$PWD/core/osd/cms/weather/osd_set_weather_request.h \
           $$PWD/core/osd/cms/weather/weather_model.h \
           $$PWD/core/osd/cms/wind/osd_cms_wind_data.h \
           $$PWD/core/osd/cms/wind/osd_set_wind_request.h \
           $$PWD/core/osd/cms/wind/wind_model.h \
           $$PWD/core/osd/model/osd_base_model.h \
           $$PWD/core/osd/model/date_time/date_time_stream_model.h \
           $$PWD/core/osd/model/inertia/gyro_cms_response_model.h \
           $$PWD/core/osd/model/inertia/gyro_stream_model.h \
           $$PWD/core/osd/model/input_mode/input_mode_cms_response_model.h \
           $$PWD/core/osd/model/position/position_cms_response_model.h \
           $$PWD/core/osd/model/position/position_stream_model.h \
           $$PWD/core/osd/model/speed/speed_cms_response_model.h \
           $$PWD/core/osd/model/speed/speed_stream_model.h \
           $$PWD/core/osd/model/water_speed/water_speed_cms_response_model.h \
           $$PWD/core/osd/model/water_speed/water_speed_stream_model.h \
           $$PWD/core/osd/model/weather/weather_cms_response_model.h \
           $$PWD/core/osd/model/weather/weather_stream_model.h \
           $$PWD/core/osd/model/wind/wind_cms_response_model.h \
           $$PWD/core/osd/model/wind/wind_stream_model.h \
           $$PWD/core/osd/stream/osd_stream.h \
           $$PWD/core/osd/stream/osd_stream_datetime.h \
           $$PWD/core/osd/stream/osd_stream_gyro.h \
           $$PWD/core/osd/stream/osd_stream_position.h \
           $$PWD/core/osd/stream/osd_stream_speed.h \
           $$PWD/core/osd/stream/osd_stream_waterspeed.h \
           $$PWD/core/osd/stream/osd_stream_weather.h \
           $$PWD/core/osd/stream/osd_stream_wind.h \
           $$PWD/http/i_cms_http.h \
           $$PWD/http/http_client_wrapper.h \
           $$PWD/messaging/IOSDStream.h \
           $$PWD/messaging/amqp/amqp_consumer_base.h \
           $$PWD/messaging/amqp/amqp_consumer_wrapper.h \
           $$PWD/messaging/amqp/amqp_options.h \
           $$PWD/messaging/serial/serial_messaging_wrapper.h \
           $$PWD/messaging/tcp/tcp_messaging_wrapper.h \
           $$PWD/store/engagement/engagement_repository.h \
           $$PWD/store/engagement/inmemory/engagement_data_correction_repository_inmem_impl.h \
           $$PWD/store/engagement/inmemory/engagement_data_repository_inmem_impl.h \
           $$PWD/store/fire_triangle/fire_triangle_repository.h \
           $$PWD/store/fire_triangle/inmemory/fire_triangle_repository_inmem_impl.h \
           $$PWD/store/gun/gun_repository.h \
           $$PWD/store/gun/inmemory/gun_command_repository_inmem_impl.h \
           $$PWD/store/gun/inmemory/gun_coverage_repository_inmem_impl.h \
           $$PWD/store/gun/inmemory/gun_feedback_repository_inmem_imp.h \
           $$PWD/store/osd/osd_repository.h \
           $$PWD/store/osd/inmemory/osd_datetime_repository_inmem_impl.h \
           $$PWD/store/osd/inmemory/osd_inertia_repository_inmem_impl.h \
           $$PWD/store/osd/inmemory/osd_input_mode_repository_inmem_impl.h \
           $$PWD/store/osd/inmemory/osd_position_repository_inmem_impl.h \
           $$PWD/store/osd/inmemory/osd_speed_repository_inmem_impl.h \
           $$PWD/store/osd/inmemory/osd_waterspeed_repository_inmem_impl.h \
           $$PWD/store/osd/inmemory/osd_weather_repository_inmem_impl.h \
           $$PWD/store/osd/inmemory/osd_wind_repository_inmem_impl.h \
           $$PWD/store/track/track_repository_publisher.h \
           $$PWD/store/track/track_repository_listener.h \
           $$PWD/store/track/track_repository.h \
           $$PWD/store/track/inmem/track_arpa_repository_inmem_impl.h \
           $$PWD/store/weapon_assign/inmemory/weapon_assignment_repository_inmem_impl.h \
           $$PWD/store/weapon_track_assign/weapon_track_assignment_repository_inmem_impl.h

SOURCES += \
           $$PWD/core/gun/cms/gun_base_model.cpp \
           $$PWD/core/gun/cms/gun_cms.cpp \
           $$PWD/core/gun/cms/barrel/gun_cms_command_barrel.cpp \
           $$PWD/core/gun/cms/barrel/gun_command_barrel_request.cpp \
           $$PWD/core/gun/cms/barrel/gun_command_barrel_response.cpp \
           $$PWD/core/gun/cms/mode/gun_cms_command_barrel_mode.cpp \
           $$PWD/core/gun/cms/mode/gun_mode_barrel_request.cpp \
           $$PWD/core/gun/cms/mode/gun_mode_barrel_response.cpp \
           $$PWD/core/gun/cms/status/gun_cms_command_status.cpp \
           $$PWD/core/gun/cms/status/gun_command_status_request.cpp \
           $$PWD/core/gun/cms/status/gun_command_status_response.cpp \
           $$PWD/core/gun/stream/gun_stream.cpp \
           $$PWD/core/gun/stream/gun_barrel/gun_feedback_barrel_model.cpp \
           $$PWD/core/gun/stream/gun_barrel/gun_feedback_barrel_stream.cpp \
           $$PWD/core/gun/stream/gun_coverage/gun_coverage_model.cpp \
           $$PWD/core/gun/stream/gun_coverage/gun_coverage_stream.cpp \
           $$PWD/core/gun/stream/gun_status/gun_feedback_status_model.cpp \
           $$PWD/core/gun/stream/gun_status/gun_feedback_status_stream.cpp \
           $$PWD/core/osd/cms/osd_cms.cpp \
           $$PWD/core/osd/cms/inertia/gyro_model.cpp \
           $$PWD/core/osd/cms/inertia/osd_cms_gyro_data.cpp \
           $$PWD/core/osd/cms/inertia/osd_set_gyro_request.cpp \
           $$PWD/core/osd/cms/input_mode/input_mode_model.cpp \
           $$PWD/core/osd/cms/input_mode/osd_cms_input_mode.cpp \
           $$PWD/core/osd/cms/input_mode/osd_input_mode_request.cpp \
           $$PWD/core/osd/cms/position/osd_cms_position_data.cpp \
           $$PWD/core/osd/cms/position/osd_set_position_request.cpp \
           $$PWD/core/osd/cms/position/position_model.cpp \
           $$PWD/core/osd/cms/speed/osd_cms_speed_data.cpp \
           $$PWD/core/osd/cms/speed/osd_set_speed_request.cpp \
           $$PWD/core/osd/cms/speed/speed_model.cpp \
           $$PWD/core/osd/cms/water_speed/osd_cms_waterspeed_data.cpp \
           $$PWD/core/osd/cms/water_speed/osd_set_waterspeed_request.cpp \
           $$PWD/core/osd/cms/water_speed/waterspeed_model.cpp \
           $$PWD/core/osd/cms/weather/osd_cms_weather_data.cpp \
           $$PWD/core/osd/cms/weather/osd_set_weather_request.cpp \
           $$PWD/core/osd/cms/weather/weather_model.cpp \
           $$PWD/core/osd/cms/wind/osd_cms_wind_data.cpp \
           $$PWD/core/osd/cms/wind/osd_set_wind_request.cpp \
           $$PWD/core/osd/cms/wind/wind_model.cpp \
           $$PWD/core/osd/model/osd_base_model.cpp \
           $$PWD/core/osd/model/date_time/date_time_stream_model.cpp \
           $$PWD/core/osd/model/inertia/gyro_cms_response_model.cpp \
           $$PWD/core/osd/model/inertia/gyro_stream_model.cpp \
           $$PWD/core/osd/model/input_mode/input_mode_cms_response_model.cpp \
           $$PWD/core/osd/model/position/position_cms_response_model.cpp \
           $$PWD/core/osd/model/position/position_stream_model.cpp \
           $$PWD/core/osd/model/speed/speed_cms_response_model.cpp \
           $$PWD/core/osd/model/speed/speed_stream_model.cpp \
           $$PWD/core/osd/model/water_speed/water_speed_cms_response_model.cpp \
           $$PWD/core/osd/model/water_speed/water_speed_stream_model.cpp \
           $$PWD/core/osd/model/weather/weather_cms_response_model.cpp \
           $$PWD/core/osd/model/weather/weather_stream_model.cpp \
           $$PWD/core/osd/model/wind/wind_cms_response_model.cpp \
           $$PWD/core/osd/model/wind/wind_stream_model.cpp \
           $$PWD/core/osd/stream/osd_stream.cpp \
           $$PWD/core/osd/stream/osd_stream_datetime.cpp \
           $$PWD/core/osd/stream/osd_stream_gyro.cpp \
           $$PWD/core/osd/stream/osd_stream_position.cpp \
           $$PWD/core/osd/stream/osd_stream_speed.cpp \
           $$PWD/core/osd/stream/osd_stream_waterspeed.cpp \
           $$PWD/core/osd/stream/osd_stream_weather.cpp \
           $$PWD/core/osd/stream/osd_stream_wind.cpp \
           $$PWD/http/http_client_wrapper.cpp \
           $$PWD/messaging/amqp/amqp_consumer_wrapper.cpp \
           $$PWD/messaging/amqp/amqp_options.cpp \
           $$PWD/messaging/serial/serial_messaging_wrapper.cpp \
           $$PWD/messaging/tcp/tcp_messaging_wrapper.cpp \
           $$PWD/store/engagement/engagement_repository.cpp \
           $$PWD/store/engagement/inmemory/engagement_data_correction_repository_inmem_impl.cpp \
           $$PWD/store/engagement/inmemory/engagement_data_repository_inmem_impl.cpp \
           $$PWD/store/fire_triangle/fire_triangle_repository.cpp \
           $$PWD/store/fire_triangle/inmemory/fire_triangle_repository_inmem_impl.cpp \
           $$PWD/store/gun/gun_repository.cpp \
           $$PWD/store/gun/inmemory/gun_command_repository_inmem_impl.cpp \
           $$PWD/store/gun/inmemory/gun_coverage_repository_inmem_impl.cpp \
           $$PWD/store/gun/inmemory/gun_feedback_repository_inmem_imp.cpp \
           $$PWD/store/osd/osd_repository.cpp \
           $$PWD/store/osd/inmemory/osd_datetime_repository_inmem_impl.cpp \
           $$PWD/store/osd/inmemory/osd_inertia_repository_inmem_impl.cpp \
           $$PWD/store/osd/inmemory/osd_input_mode_repository_inmem_impl.cpp \
           $$PWD/store/osd/inmemory/osd_position_repository_inmem_impl.cpp \
           $$PWD/store/osd/inmemory/osd_speed_repository_inmem_impl.cpp \
           $$PWD/store/osd/inmemory/osd_waterspeed_repository_inmem_impl.cpp \
           $$PWD/store/osd/inmemory/osd_weather_repository_inmem_impl.cpp \
           $$PWD/store/osd/inmemory/osd_wind_repository_inmem_impl.cpp \
           $$PWD/store/track/track_repository.cpp \
           $$PWD/store/track/inmem/track_arpa_repository_inmem_impl.cpp \
           $$PWD/store/weapon_assign/inmemory/weapon_assignment_repository_inmem_impl.cpp \
           $$PWD/store/weapon_track_assign/weapon_track_assignment_repository_inmem_impl.cpp
